version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
  # using this image because it works for macbook M1's
    image: niks123123/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "send-payment:1:1,payment-response:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock